import { StyleSheet } from "react-native";

export const createStyles = (vars: Record<string, string>) => StyleSheet.create({
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: vars["--text-secondary"],
  },
  emptyText: {
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
    paddingHorizontal: 20,
    color: vars["--text"],
  },
  emptySubText: {
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    paddingHorizontal: 20,
    color: vars["--text-secondary"],
  },
  list: {
    paddingBottom: 20,
    paddingTop: 10,
    width: "95%",
    alignSelf: "center",
  },
  errorText: {
    textAlign: 'center',
    marginBottom: 12,
    marginHorizontal: 16,
    fontSize: 14,
    color: vars["--error"],
  },
  retryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 16,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  searchInput: {
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 16,
    marginVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: vars["--background-secondary"],
    color: vars["--text"],
    backgroundColor: vars["--surface"],
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 20,
  },
  modalContent: {
    width: '85%',
    padding: 20,
    borderRadius: 12,
    backgroundColor: vars["--surface"],
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
    color: vars["--text"],
  },
  modalSubtitle: {
    fontSize: 14,
    marginBottom: 16,
    color: vars["--text-secondary"],
  },
  reasonInput: {
    borderWidth: 1,
    borderColor: vars["--outline"],
    borderRadius: 8,
    padding: 12,
    marginBottom: 20,
    textAlignVertical: 'top',
    minHeight: 120,
    fontSize: 14,
    color: vars["--text"],
    backgroundColor: vars["--surface"],
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalButton: {
    borderRadius: 8,
    paddingVertical: 12,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontWeight: '600',
    color: vars["--text"],
  },
  keyboardAvoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  primary: {
    color: vars["--primary"],
  },
  listContent: {
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  flexGrow: {
    flexGrow: 1,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  stickyHeader: {
    backgroundColor: vars["--surface"],
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: vars["--outline"],
    zIndex: 10,
  },
  fab: {
    position: 'absolute',
    borderRadius: 28,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    backgroundColor: vars["--primary"],
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  loadingOverlayText: {
    marginTop: 16,
    fontSize: 16,
  },
});